#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##  Copyright (c) 2015 the Gradle project.
##
##  Permission is hereby granted, free of charge, to any person obtaining a copy
##  of this software and associated documentation.
##  The following conditions are met:
##
##  1. Redistributions of source code must retain the above copyright notice,
##     this notice and this list of conditions.
##  2. Redistributions of source code must occur in the same form as the original.
##
##  3. Neither the name of the Gradle Company nor the names of its contributors
##  may be used to endorse or promote products of this software and associated
##  documentation.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
##  AND ANY OTHER SOFTWARE IS DISCLAIMED. ANY EVENT SHALL THE COPYRIGHT HOLDER OR
##  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, OR INDIRECT, INCIDENTAL, SPECIAL,
##  EXEMPLARY, OR CONSEQUENTIAL DAMAGES.
##  THE SOFTWARE IS NOT LIMITED TO THE USE OF THE SOFTWARE OR OTHER SOFTWARE
##  OR CONSEQUENTIAL DAMAGES (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING OUT
##  OF THE SOFTWARE OR USE OF ITS SOFTWARE OR OTHER SOFTWARE OR THE PRODUCTS OF
##  THIS SOFTWARE OR USE OF ANY OTHER SOFTWARE OR THE PRODUCTS OF THE SOFTWARE.
##
##  In no event, or in connection with the use of the software, the product is
##  provided "as is", without warranty of any kind, either express or implied.
##
##  The entire risk as to the quality and performance of the product is assumed
##  by the user.
##
##  The above copyright holders and contributors disclaim all warranties,
##  including but not limited to, the implied warranties of merchantability,
##  fitness for a particular purpose, and non-infringement.
##
##  In no event shall the copyright holders or contributors be liable for any
##  direct, indirect, incidental, special, exemplary, or consequential damages,
##  including but not limited to, procurement of substitute goods or services;
##  loss of use, data, or profits; or business interruption; however caused and
##  on any theory of liability, whether in contract, strict liability, or tort
##  (including negligence or otherwise) arising in any way out of the use of the
##  software, even if advised of the possibility of such damages.
##
##  See the License for the specific language governing permissions and
##  limitations under the License.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a literal symlink
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done
SAVED="$(pwd -P)"
cd "$(dirname "$PRG")"/ >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use $GRADLE_OPTS or JAVA_OPTS to pass JVM options to the script.
DEFAULT_JVM_OPTS=""

# Use the maximum available, however you may not want to use the wrapper in this environment.
if [ "x$JAVA_HOME" != "x" ]; then
  if [ -x "$JAVA_HOME/jre/sh/java" ]; then
    JAVA_EXE="$JAVA_HOME/jre/sh/java"
  else
    JAVA_EXE="$JAVA_HOME/bin/java"
  fi
  if [ ! -x "$JAVA_EXE" ]; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
    exit 1
  fi
else
  JAVA_EXE="java"
fi

# Determine the location of the Gradle distribution.
if [ -n "$APP_HOME/gradle/wrapper/gradle-wrapper.properties" ]; then
  CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
fi

# If the gradle-wrapper.jar is missing, download it.
if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
  echo "Downloading Gradle Wrapper..."
  mkdir -p "$APP_HOME/gradle/wrapper"
  curl -sSLo "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" https://raw.githubusercontent.com/gradle/gradle/v8.10.2.0/gradle/wrapper/gradle-wrapper.jar
fi

exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
